version: '3'

services: 
    apache: 
        # Build only once, then use local image
        #build: .docker
        image: symfony5
        container_name: symfony_apache
        restart: always
        working_dir: /var/www
        ports: 
            - 88:80
        environment: 
            DATABASE_MYSQL_URL: mysql://user:pass@mysql:3306/mydb
            DATABASE_POSTGRES_URL: postgres://user:pass@postgres:5432/pgdb
        volumes:
            ##################################################
            # GIT BRANCHES SHOULD BE PULLED INSIDE CONTAINER #
            ##################################################
            - app:/var/www

            # HOME
            - ${DIRECTORY}/.docker/.home/.bashrc:/root/.bashrc
            - ${DIRECTORY}/.docker/.home/.gitconfig:/root/.gitconfig
            - ${DIRECTORY}/.docker/.home/user-prompt.sh:/root/user-prompt.sh
            - ${DIRECTORY}/.docker/.home/prompt:/root/prompt
            - ${DIRECTORY}/.docker/.home/.bash_it:/root/.bash_it
            - ${DIRECTORY}/.docker/.home/.bash-it:/root/.bash-it

            # used to update local config in needed (like .docker)
            - ${DIRECTORY}:/SYMFONY

            - ${DIRECTORY}/.docker/conf/httpd/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
            - vscode-server:/root/.vscode-server
        networks:
            - sym

    mysql:
        image: mysql:5.6
        container_name: symfony_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
        # For Windows users
        command: "--innodb_use_native_aio=0"
        volumes:
            - ${DIRECTORY}/.docker/conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - mysql:/var/lib/mysql/
        ports:
            - 3306:3306
        networks: 
            - sym

    # https://hub.docker.com/_/postgres
    postgres:
        build: .docker/postgres
        container_name: symfony_postgres
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: pgdb
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            #- postgres:/data/postgres
            - postgres:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        networks:
            - sym
        

    # https://hub.docker.com/_/rabbitmq
    rabbitmq:
        build: .docker/rabbitmq
        container_name: symfony_rabbitmq
        restart: always
        networks:
            - sym

    ######
    # doc:
    # https://www.pgadmin.org/docs/pgadmin4
    ######
    pgadmin: 
        image: dpage/pgadmin4
        container_name: symfony_pgadmin
        environment: 
            # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
            PGADMIN_DEFAULT_EMAIL: admin@local.host
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 80
            PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
        volumes: 
            # https://www.pgadmin.org/docs/pgadmin4/latest/import_export_servers.html
            - ${DIRECTORY}/.docker/conf/pgadmin/servers.json:/pgadmin4/servers.json
            # https://www.postgresql.org/docs/9.1/libpq-pgpass.html
        ports: 
            - 8888:80
        networks:
            - sym

networks:
    sym:

volumes:
    app:
    postgres:
    mysql:
    vscode-server:
